### ISSUE TITLE
SafeEmbedGenerator - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by ValWasBetter** [KyzaGitHub/Khub#15]
not working :/
![image](https://user-images.githubusercontent.com/38843701/64708242-93c6ec80-d4b4-11e9-90d1-d4dbae388511.png)

![image](https://user-images.githubusercontent.com/38843701/64708315-b953f600-d4b4-11e9-9233-96eca10862ba.png)

**Comment by KyzaGitHub** [comment]
That error doesn't have anything to do with SafeEmbedGenerator. You're probably just in a channel that you don't have permissions to send embedded links in.

**Comment by KyzaGitHub** [comment]
It seems I accidentally closed this issue.
