### ISSUE TITLE
SafeEmbedGenerator - Plugin - [Status: Broken]

### ISSUE THREAD

**Issue by keketiger** [KyzaGitHub/Khub#16]
This is ONLY to report that this plugin (as of 2019-05-02) IS NOT working!

**Comment by KyzaGitHub** [comment]
The plugin is working as of 09/17/2019. Would you mind stating your problem?

**Comment by keketiger** [comment]
I do not have a button at the bottom right

**Comment by KyzaGitHub** [comment]
This is most likely because you are in a channel that you don't have permission to send embedded links in. Could you press `Ctrl+Shift+i` (or `Cmd` on macOS) and screenshot the menu that appears?

**Comment by KyzaGitHub** [comment]
Closed for inactivity.
