### ISSUE TITLE
[DarkDark] Server Folders aren't themed

### ISSUE THREAD

**Issue by underscore11-wh** [KyzaGitHub/Khub#27]
**What plugin does the bug occur in?**
DarkDark

**What version is the plugin?**
2.1.2

**Describe the bug.**
Opened Server Folders do not appear to be themed with one of the shades of grey

**Comment by KyzaGitHub** [comment]
Can you provide a screenshot?

**Comment by underscore11-wh** [comment]
![image](https://user-images.githubusercontent.com/55677189/65476285-42fdaf00-de37-11e9-81cb-70490d68907d.png)
Its possible it is themed, it is just such a similar color to the default that I can't tell.

**Comment by KyzaGitHub** [comment]
Yes, that is themed.

This is what it looks like unthemed.

![image](https://user-images.githubusercontent.com/40003440/65476366-a811ce80-de50-11e9-8483-a630f7c626e4.png)
