### ISSUE TITLE
[SafeEmbedGenerator] 

### ISSUE THREAD

**Issue by Perpetucake** [KyzaGitHub/Khub#44]
## Before submitting a bug report, make sure you have reproduced the bug with all other themes and plugins disabled (excluding mine).

**What version is the plugin?**
[2.0.0]

**Describe the bug.**
SafeEmbedGenerator v2.0.0: TypeError: Cannot read property 'parse' of null

**Give steps to reproduce the bug.**
Click on literally any channel or direct message.

Ever since the update stating a rewrite. Confirmed will all other plugins disabled.

**Comment by OFWModz** [comment]
This issue seems to come from:

`if (this.hasPermission()) {
                  var daButtons = document.querySelector(
                    KSS.parse("|highBackgroundOpacity buttons|")
                  );`

Returning null. Please fix.

**Comment by KyzaGitHub** [comment]
The error comes from not having KSSLibrary installed. The plugin should ask you but fails to do so. This will be fixed soon.

**Comment by OFWModz** [comment]
As a temporary fix, use save this to your plugin folder bois.

https://raw.githubusercontent.com/KyzaGitHub/Khub/master/Libraries/KSS/1KSSLibrary.plugin.js

**Comment by KyzaGitHub** [comment]
Fixed for all my plugins that use it in the latest push.
