### ISSUE TITLE
[GhostMessage] 

### ISSUE THREAD

**Issue by bvnnd** [KyzaGitHub/Khub#50]
**What version is the plugin?**
[1.3.3]
ZeresPluginLibrary v1.2.10 installed
BD v0.3.3
BDD v0.2.21

**Describe the bug.**
[Everytime i try to toggle the plugin my discord crash]

Any idea why ?

**Comment by KyzaGitHub** [comment]
It could be because you haven't reloaded Discord to the new UI update.

**Comment by bvnnd** [comment]
I did actually, even before that update it was crashing for me.

**Comment by KyzaGitHub** [comment]
I'll check it out soon. You can get support meanwhile [here](https://discord.gg/c9ESSur).

**Comment by bvnnd** [comment]
Fixed using KSS Library
