### ISSUE TITLE
CustomDiscordIcon - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by harrisr2930** [KyzaGitHub/Khub#8]
I've tried multiple different images, but I'm not seeing any changes. Is there a specific size or can you give any other clarification?

**Comment by KyzaGitHub** [comment]
Could you give me the full path to the files that don't work, please?

**Comment by harrisr2930** [comment]
Sure. For instance an image like this: "C:\Users\Lee\Pictures\Emotes\FeelsBadMan.png" I removed the quotations and the message telling me it had to be a .JPEG or .png went away, but it still never showed up.
